### ISSUE TITLE
Problem setting up softap

### ISSUE THREAD

**Issue by denizonural** [spark/softap-setup-js#15]
Hi,

I'm not sure if this is a trivial rookie problem, but would appreciate all help and any future guidance to setting an access point with photon :)

I am using terminal to set softAp on photon. I installed node.js, can use particle cli to setup photon, and installed softap-setup.js. But when I try to declare a sap object (  I type: var sap = new SoftAPSetup({ protocol: 'http' });    ) I only get errors:
-bash: syntax error near unexpected token `('

Clearly terminal isn't recognizing the softap commands/constructors. What should I do?

Thanks
Deniz

**Comment by brycekahle** [comment]
Your terminal/shell does not support node.js code directly. You either need to save your code in a file, and run it with node (i.e. `node softap.js`) or use the node repl by just typing `node` and you can put your code in there. Make sure you `require` the module first in both cases.

**Comment by m-mcgowan** [comment]
Looks like this was a misunderstanding about how to run node.
