### ISSUE TITLE
What's the deal with browser functionality?

### ISSUE THREAD

**Issue by benhassara** [spark/softap-setup-js#20]
At the top of this repo's README we've got this message:

> !! HTTP mode unstable: Due to a firmware bug, the HTTP protocol is unreliable from most browsers. HTTP mode is not recommended at this time.

Then down at the bottom, where there are instructions for using the lib in the browser there's this:

> NOTE: Only the "http" protocol works in the browser. "tcp" will fail because the browser does not allow direct access to sockets.

Am I supposed to conclude from these two things that SoftAP does not work at all in the browser?

**Comment by towynlin** [comment]
Give it a shot! Unless you see it work, I think that's a reasonable assumption at this point. This project hasn't been taken over the finish line. It did come up in a meeting this week at Particle though, so it might bubble up the priority list in the coming sprints. As always, PRs welcome.

**Comment by anigo333** [comment]
it does work on most browsers however recent IOS 10 update has caused it to not work on ios safari and phonegap. 

What's interesting is that the actual issue in the firmware has been fixed as per the issues comments but I wonder why it is still is listed as a warning here.
