### ISSUE TITLE
sap.deviceInfo not working in particle setup

### ISSUE THREAD

**Issue by danielmapar** [spark/softap-setup-js#23]
Node: v4.6.0
OS: Windows 10 x64
Particle-cli: 1.17

When particle setup runs (inside commands/WirelessCommand.js):

``` javascript
sap.deviceInfo(pubKey).on('error', function(err) {

            if (err.code === 'ECONNRESET') {
                return;
            }
            retry = setTimeout(info, 1000);
        });
```

Err returns:

<img width="464" alt="screen shot 2016-10-30 at 8 12 41 pm" src="https://cloud.githubusercontent.com/assets/4336805/19840629/6f813e86-9ee1-11e6-8571-d2d28ec38427.png">

Also, if I run softap-setup (4.0.1) standalone same issue occurs:

<img width="485" alt="screen shot 2016-10-30 at 8 37 03 pm" src="https://cloud.githubusercontent.com/assets/4336805/19840639/b5c9e078-9ee1-11e6-86dd-aaa30db52597.png">

**Comment by danielmapar** [comment]
The device is connected to the laptop in listening mode (blinking blue), and before that I did a factory restore.

Another ticket that shows this issue: https://community.particle.io/t/solved-unknown-issue-with-photon-edit-photon-cannot-connect-to-cloud/19293/25

**Comment by monkbroc** [comment]
OK. Thanks for reporting this.

**Comment by m-mcgowan** [comment]
@danielmapar  thanks for the report. I'm not able to reproduce it with the information we have. I hope you can provide more details:

- Please tell me the system firmware version on the Photon that is experiencing this issue. (Put the device in listening mode, then run `particle serial identify`. )
- Can you post your `test.js` script for the standalone test so I can be sure we are testing the same thing.
- does the problem happen every time, or just sometimes?

**Comment by m-mcgowan** [comment]
I've managed to reproduce this by modifying `example/basic-setup.js`.
