### ISSUE TITLE
returned device-id should be toLowercased

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/softap-setup-js#32]
Received a report that users using this library sometimes get device-ids back from the device with uppercase letters which can interfere with claiming.  I think it's safe to assume our device-ids are case insensitive, and although we should catch this on the API-side as well, it'll be more clear / consistent if we enforce this everywhere.

**Comment by m-mcgowan** [comment]
Duplicate of https://github.com/spark/softap-setup-js/issues/18 which is already fixed in the latest release. :-)
