### ISSUE TITLE
Undefined it not an object evaluating 'dat.b' softap

### ISSUE THREAD

**Issue by incorvia** [spark/softap-setup-js#33]
We are using softap-setup in a react native environment. In order to get this library to work we needed to use version 4.0.1 because 4.0.2 and 4.0.3 both thrown an error:

    undefined it not an object evaluating 'dat.b' softap

However, since 4.0.1 is pinned to node-rsa 0.2.3 (which is problematic, see: https://github.com/spark/softap-setup-js/issues/22) we needed to patch 4.0.1's package.json to 0.4.2. I just thought I'd mention our troubles as there does seem to be an issue with 4.0.2 and 4.0.3.

**Comment by m-mcgowan** [comment]
Thank you for the issue report. Could you provide steps to reproduce the issue? Once we have this we are in a position to try to reproduce the bug. Thanks!
