### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by markterrill** [spark/softap-setup-js#38]
Hi,

Needed typescript support for the new Smartfire BBQ app, so engaged a developer to add it in:

https://www.npmjs.com/package/softap-setup-ts

Trust it's useful!

Mark

**Comment by monkbroc** [comment]
That's great! Thanks for sharing! I added your library to our list of community supported libraries.

https://docs.particle.io/reference/community/#typescript

**Comment by markterrill** [comment]
Thanks team,

Could you add a reference to the softap github repo as well? I’d never have looked in the community page for additional packages for softap. Hoping the money and time that went into this update actually saves someone else the headache as typescript is the defacto now for most frameworks (angular 2+ / even react on windows defaults to typescript instead of babel).

I imagine getting tight tie in with the likes of ionic framework is a key goal of Particle to help developers get going quickly. If so, really should grab my code and bake it into the main softap stream and use the tsc down compiled version if folk need a legacy javascript version.

Mark

**Comment by monkbroc** [comment]
I added a note at the top of the README in the GitHub repo. Thanks again!
