### ISSUE TITLE
OPEN networks

### ISSUE THREAD

**Issue by anthonywebb** [spark/softap-setup-js#4]
Has this been tested on an open network?  I am seeing a failure when connecting to open networks but networks with passwords connect fine.

**Comment by brycekahle** [comment]
Do you know what version of firmware is running on your Photon?

**Comment by anthonywebb** [comment]
I am running the latest 4.4 release @brycekahle

**Comment by brycekahle** [comment]
We are going to do some testing. I'll keep you posted on results. Thanks for the report!

**Comment by anthonywebb** [comment]
Thanks @brycekahle, I should also note that the particle iOS app will connect my photon to those open networks just fine so I assume it is something specific to this lib.

**Comment by brycekahle** [comment]
@anthonywebb can you try using the [particle-cli](https://github.com/spark/particle-cli) against your open network? We did some internal testing and that works. The CLI uses this library, so I want to identify if there is a potential regression in this library.

**Comment by anthonywebb** [comment]
Yes, the CLI is working for me.  So it uses this same lib?

I am finding that connecting to secure network works fine in safari, but OPEN networks do not work in safari.  But, with the same code both secure and open networks work in chrome just fine, same for both mobile and desktops alike, argh!

**Comment by brycekahle** [comment]
Are you using this library? I don't see any usage of it in the script you posted. It looks like you are hitting the Photon endpoints directly?

**Comment by anthonywebb** [comment]
@brycekahle I am hitting the photon directly, but wanted to me sure that the payload needed for open networks was indeed correct and functioning.  It appears to be so I am onto looking for the variations in how chrome and safari send those payloads.  Thanks again for the help.
